### ISSUE TITLE
smoothSplines() crashes the R session when I manually define the knots

### ISSUE THREAD

**Issue by agila5** [matthias-da/robCompositions#21]
Dear package authors. I've created this issue to highlight a problematic behaviour in `smoothSplines()`. See the code below

``` r
# taken from ?robCompositions::smoothSplines
SepalLengthCm <- iris$Sepal.Length
Species <- iris$Species
iris1 <- SepalLengthCm[iris$Species==levels(iris$Species)[1]]
h1 <- hist(iris1, nclass = 12, plot = FALSE)
midx1 <- h1$mids
midy1 <- matrix(h1$density, nrow=1, ncol = length(h1$density), byrow=TRUE)

robCompositions::smoothSplines(
  k = 3, 
  l = 2, 
  alpha = 1e-5, 
  data = midy1, 
  xcp = midx1, 
  knots = seq(4.4, 5.6, length.out = 5)
)
```

I am certainly doing something wrong, but I must also admit that it's slightly annoying that the code crashes the R session.

**Comment by matthias-da** [comment]
Thanks a lot for pointing this out. 

Some authors define only inner knots, some take the definition that the "outer knots" are also counting as knots. This implementation use the latter one. However, this wasn't visible in the help file. In addition, there was an message, but within the C++ code, displayed but with follow-up crash. This I now took in front, so that R will not crash and the user gets information about it before C++ code is executed.  

Check, this works now with the GitHub version of robCompositions (and your choice of knots should give a proper message now)

```{r}
library(devtools)
install.packages("matthias-da/robCompositions")
library(robCompositions)
# taken from ?robCompositions::smoothSplines
SepalLengthCm <- iris$Sepal.Length
Species <- iris$Species
iris1 <- SepalLengthCm[iris$Species==levels(iris$Species)[1]]
h1 <- hist(iris1, nclass = 12, plot = FALSE)
midx1 <- h1$mids
midy1 <- matrix(h1$density, nrow=1, ncol = length(h1$density), byrow=TRUE)

robCompositions::smoothSplines(
  k = 3, 
  l = 2, 
  alpha = 1e-5, 
  data = midy1, 
  xcp = midx1, 
  knots = seq(4, 6, length.out = 5)
)
```

**Comment by agila5** [comment]
Thanks! I think that there is a typo in the last commit since, AFAICT, the location of the knots should be relative to the argument `xcp` while, currently, they are based on the `data` argument (i.e. the heights of the histogram in that example): 

https://github.com/matthias-da/robCompositions/blob/6d0de678fd646163a360e2067349b1852099e779/R/splineDensity.R#L93-L99

I guess that should be something like: `min(knots) <= min(xcp)` and analogously for the max.

**Comment by matthias-da** [comment]
Thanks - should not do this in a great hurry ...
